### ISSUE TITLE
Enable/disable pairing configuration example in docs not good for Lovelace

### ISSUE THREAD

**Issue by ronschaeffer** [danielwelch/hassio-zigbee2mqtt#105]
From HA version 0.86, the very helpful example configuration for creating an enable/disable pairing switch does not work (unless inherited from the States frontend) since Lovelace ignores groups.yaml. The Zigbee card does not appear in the Lovelace front end.

You could add a note to create a Lovelace card with the following parameters instead of modifying groups.yaml.

```
type: entities
entities:
  - entity: input_boolean.zigbee_permit_join
  - entity: timer.zigbee_permit_join
  - entity: sensor.bridge_state
show_header_toggle: false
title: Zigbee
```
