### ISSUE TITLE
error using !secret for user and password in zigbee2mqtt configuration file

### ISSUE THREAD

**Issue by jcampoy** [danielwelch/hassio-zigbee2mqtt#147]
Hi, it seems secrets are not allowed in new version 1.3.0, this is part of my configuration file, and after starting the add-on fails:

```yaml
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.0.12:1883'
  user: !secret mqtt_username
  password: !secret mqtt_password
  client_id: BEE_CLIENT
  reject_unauthorized: true
  include_device_information: true
```

And the error:
```

2019-04-14T22:45:14: PM2 log: App [npm:0] starting in -fork mode-
2019-04-14T22:45:14: PM2 log: App [npm:0] online
> zigbee2mqtt@1.3.0 start /zigbee2mqtt-1.3.0
> node index.js
/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:173
  throw generateError(state, message);
  ^
YAMLException: unknown tag !<!secret> at line 8, column 30:
      user: !secret mqtt_username
                                 ^
    at generateError (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at composeNode (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:1428:7)
    at readBlockMapping (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readBlockMapping (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at load (/zigbee2mqtt-1.3.0/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.3.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!
     /root/.npm/_logs/2019-04-14T20_45_17_525Z-debug.log
```
