### ISSUE TITLE
rtscts variable is not written to /share/zigbee2mqtt/configuration.yaml

### ISSUE THREAD

**Issue by jerrychong25** [danielwelch/hassio-zigbee2mqtt#171]
Hi all,

I have successfully installed **hassio-zigbee2mqtt** V1.4.0 with CC2530.

My Config in **hassio-zigbee2mqtt**, as per below:
```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://homeassistant",
  "serial_port": "/dev/ttyUSB0",
  "devices": [],
  "network_key": [],
  "mqtt_user": "*****",
  "mqtt_pass": "*****",
  "include_device_information": true,
  "reject_unauthorized": false,
  "rtscts": false
}
```

However, the final content of **/share/zigbee2mqtt/configuration.yaml** after I started the **hassio-zigbee2mqtt**, as per below:
```
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  include_device_information: true
  password: *****
  reject_unauthorized: false
  server: mqtt://homeassistant
  user: *****
permit_join: false
serial:
  port: /dev/ttyUSB0
```

The **rtscts** variable mentioned in [documentation](https://www.zigbee2mqtt.io/configuration/configuration.html) is not saved into the **configuration.yaml**.

Could anyone assist on how to resolve this issue?

Thanks.

**Comment by jerrychong25** [comment]
It do appears, but it appears on top of devices variable.

```
advanced:
  rtscts: false
devices:
  '0x00124b001bc74813':
    friendly_name: '0x00124b001bc74813'
    retain: false
```
