### ISSUE TITLE
Not retaining status of bulbs on restart

### ISSUE THREAD

**Issue by DerpyDoom** [danielwelch/hassio-zigbee2mqtt#237]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 1.6.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):** Raspberry Pi 2

**Description of problem:**

On reboot it seems that HassIO doesn't retain the status of bulbs and other zigbee devices. For example If I turn on a lamp and do a reboot, it is off in the system but on in reality (glowing). 

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto",
    "user": "(hidden)",
    "password": "(hidden)"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": false
  },
  "advanced": {
    "pan_id": (hidden),
    "channel": (hidden),
    "network_key": [
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**Your logs from Hass.io**

No errors to be found.

**Comment by Tekno-man** [comment]
I have the exact same problem with 2 hue ambience bulbs. The state also doesn't update until you send a command throigh HA or you power cycle the bulb.

**Comment by 1300371** [comment]
Same here. I have to restart zigbee2mqtt addon to make my sensors available again.

**Comment by ciotlosm** [comment]
This is not related to `hassio-zigbee2mqtt`. Maybe post an issue with https://github.com/Koenkk/zigbee2mqtt.io, however if I'm not mistaken, there should be messages sending "reports" on the current state, at least for active devices.

**Comment by DrakeSeven** [comment]
To retain the status of devices on restart and reboot, you need to add the following into your configuration.yaml:
```
mqtt:
  discovery: true
  broker: [YOUR MQTT BROKER]  # Remove if you want to use builtin-in MQTT broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```
