### ISSUE TITLE
Editing lovelace YAML as suggested in doc: "Unable to parse YAML: YAMLException: duplicated mapping key"

### ISSUE THREAD

**Issue by hista** [danielwelch/hassio-zigbee2mqtt#249]
Hi, the doc (https://github.com/danielwelch/hassio-zigbee2mqtt) suggests this:

> And add something like the following to your lovelace YAML file (if using YAML mode):

```
type: entities
entities:
  - entity: input_boolean.zigbee_permit_join
  - entity: timer.zigbee_permit_join
  - entity: sensor.bridge_state
show_header_toggle: false
title: Zigbee
```

But I can't save the lovelace YAML file because of this error:
https://i.imgur.com/L1EHuBK.png
Could you please tell me how to solve it?
Thanks for your kind help :-)

**zigbee2mqtt add-on version: 1.6.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):Hass.io running on a Raspbian with docker-ce

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": true,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto:1883",
    "user": "****",
    "password": "*******"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

**Your logs from Hass.io**
  zigbee2mqtt:info 11/1/2019, 10:59:11 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:01:51 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:04:31 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:07:11 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:09:51 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:12:31 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:15:11 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:17:51 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:20:31 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:23:11 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:25:51 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:28:31 PM Successfully reenabled joining
  zigbee2mqtt:info 11/1/2019, 11:31:11 PM Successfully reenabled joining

**Comment by danielwelch** [comment]
This isn’t related to the add-on and looks like a basic yaml syntax issue. From the screenshot, it looks like you define title twice at the same level. Whenever you have an issue like this, try just copying your YAML into an online parser/linter. There’s plenty online.

**Comment by DmitriiMi** [comment]
Same error, how to fix?

```
title: HomeBox
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.dmitrii
      - entity: sun.sun
    cards: []
    
type: entities
entities:
  - entity: input_boolean.zigbee_permit_join
  - entity: timer.zigbee_permit_join
  - entity: sensor.bridge_state
show_header_toggle: false
title: Zigbee
```

<img width="404" alt="Снимок экрана 2020-01-05 в 15 37 29" src="https://user-images.githubusercontent.com/14926347/71780262-740e8380-2fd1-11ea-8f3f-86d05d251c70.png">
<img width="419" alt="Снимок экрана 2020-01-05 в 15 37 37" src="https://user-images.githubusercontent.com/14926347/71780264-740e8380-2fd1-11ea-8785-1432e2e87cdc.png">
