### ISSUE TITLE
Debug information not written to log file

### ISSUE THREAD

**Issue by arjanvroege** [danielwelch/hassio-zigbee2mqtt#287]
I've the same issue, is the information normally written to a log file?

_Originally posted by @arjanvroege in https://github.com/danielwelch/hassio-zigbee2mqtt/issues/251#issuecomment-576446876_

**Comment by mf-social** [comment]
Same issue here. I tried to report a pairing issue on the zigbee2mqtt issue tracker and needed full debugging. Shows fine in the log window for the addon but does not output to the file.

**Comment by upwindanderl** [comment]
Same problem here. 

Crispy new system: PI3 with a  CC1352P-2 and hassio addon 1.11.0 -stable 
I'm even not able to see in the ui console some bridge pairing on/off

I also tried to switch on the log in the config :

```

data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto:1883'
  user: mqtt
  password: hassio
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.07__Embed_with_CMSIS-DAP_L43003AX-if00
advanced:
  pan_id: 5731
  channel: 15
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
log_level: info
log_output:
  - console
```

after restart i get always this:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-03-11T18:17:26: PM2 log: Launching in no daemon mode
2020-03-11T18:17:26: PM2 log: App [npm:0] starting in -fork mode-
2020-03-11T18:17:26: PM2 log: App [npm:0] online
> zigbee2mqtt@1.11.0 start /zigbee2mqtt-1.11.0
> node index.js
zigbee2mqtt:info  2020-03-11 18:17:32: Logging to console and directory: '/share/zigbee2mqtt/log/2020-03-11.18-17-31' filename: log.txt
zigbee2mqtt:info  2020-03-11 18:17:32: Starting zigbee2mqtt version 1.11.0 (commit #unknown)
zigbee2mqtt:info  2020-03-11 18:17:32: Starting zigbee-herdsman...
zigbee2mqtt:info  2020-03-11 18:17:34: zigbee-herdsman started
zigbee2mqtt:info  2020-03-11 18:17:34: Coordinator firmware version: '{"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20191106}}'
zigbee2mqtt:info  2020-03-11 18:17:34: Currently 0 devices are joined:
zigbee2mqtt:info  2020-03-11 18:17:34: Zigbee: disabling joining new devices.
zigbee2mqtt:info  2020-03-11 18:17:34: Connecting to MQTT server at mqtt://core-mosquitto:1883
zigbee2mqtt:info  2020-03-11 18:17:36: Connected to MQTT server
zigbee2mqtt:info  2020-03-11 18:17:36: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
zigbee2mqtt:info  2020-03-11 18:17:36: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.11.0","commit":"unknown","coordinator":{"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20191106}},"log_level":"info","permit_join":false}'
```

**but nothing more** :-(
