### ISSUE TITLE
Documentation of Mqtt Configuration in Readme

### ISSUE THREAD

**Issue by duesseldorferjung** [danielwelch/hassio-zigbee2mqtt#324]
After searching a lot on the HA Forum how to maintain the status of my zigbee2mqtt devices after restart, I was pointed to a specific mqtt configuration.
It does work for me and if it is correct, I feel it can probably help others if it is document in the readme here rather than only on the zigbee2mqtt website.
https://www.zigbee2mqtt.io/integration/home_assistant.html

```
mqtt:
  discovery: true
  broker: [YOUR MQTT BROKER]  # Remove if you want to use builtin-in MQTT broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```
