### ISSUE TITLE
unable to use network_key_string in the addon config

### ISSUE THREAD

**Issue by jcampoy** [danielwelch/hassio-zigbee2mqtt#335]
Addon Version zigbee2mqtt 1.13.0 

Unable to save configuration if I try to use a **network_key_string** and an empty **network_key**

```
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got
{
    'data_path': '/config/zb2mqtt',
    'devices': 'devices.yaml',
    'groups': 'groups.yaml',
    'homeassistant': True,
    'permit_join': False,
    'mqtt': {
        'base_topic': 'zb2mqtt',
        'client_id': 'zb2mqtt',
        'server': 'mqtt: //192.168.0.99:1883',
        'user': '!secret mqtt_username',
        'password': '!secret mqtt_password',
        'reject_unauthorized': True
    },
    'serial': {
        'port': '/dev/ttyACM0',
        'disable_led': True
    },
    'advanced': {
        'pan_id': 6754,
        'channel': 11,
        'network_key_string': 'loquesea',
        'network_key': [], 'ext_pan_id_strin...
```

If I do use the classic way via network_key, it works...

**Comment by jcampoy** [comment]
The issue is not fixed. Reproduced on zigbee2mqtt Add-on version 1.14.1

**Comment by ciotlosm** [comment]
@jcampoy Can you provide a (random) example of the actual string you're trying to use in the string?
My understanding is that it should be something like: "1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13"

**Comment by ciotlosm** [comment]
Works for me on my test env with
```
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key_string: '1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13'
  network_key: []
  availability_blocklist: []
  availability_passlist: []
```
