### ISSUE TITLE
DeCONZ support in config file

### ISSUE THREAD

**Issue by renedis** [danielwelch/hassio-zigbee2mqtt#356]
serial:
  port: /dev/ttyACM0

This is used normally but since zigbee2mqtt 1.14 support has come for the Conbee sticks it needs te following config in hassio. Yet this isn't allowed at this point:

serial:
  adapter: deconz

See also:
https://www.zigbee2mqtt.io/information/supported_adapters.html
https://github.com/Koenkk/zigbee-herdsman/issues/72

**Comment by renedis** [comment]
same issue here:
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/336

there is already a pull-request.....

**Comment by riddledaxis** [comment]
@danielwelch @twanislas

 I appreciate that Daniel has already merged the fix for this issue, but I installed v1.14.3 of the add-on today and if I enter 
```
serial:
   adapter: deconz 
```
into the add-on's configuration, I get this error and I am unable to save it.

Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt', 'server': 'mqtt://core-mosquitto', 'user': '!secret zigbee2mqtt_user', 'password': '!secret zigbee2mqtt_pswd'}, 'serial': {'adapter': 'deconz'}, 'advanced': {'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13], 'availability_blacklist': []}, 'ban': [], 'whitelist': [], 'queue'...	 

If I use port: dev/ttyACM02 I then get the "Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms) " problem.

In the add-on's schema it references the above fix, so I should be able to add the adapter rather than port:

"serial": {
    "port": "str",
    "disable_led": "bool?",
    "adapter": "match(^zstack|deconz$)?"

Please advise what I am doing wrong?

I have HA 0.114.0 running on HassOS 4.12 and Supervisor 232 in a Proxmox vm

**Comment by Twanislas** [comment]
Hi !

Works flawlessly for me, here's my config :
```yaml
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: ZigBee
  server: 'mqtt://core-mosquitto'
  user: homeassistant
  password: REDACTED
serial:
  adapter: deconz
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_REDACTED-if00
advanced:
  pan_id: REDACTED
  channel: 25
  network_key:
    - REDACTED
  availability_blacklist: []
  report: true
ban: []
whitelist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
device_options:
  transition: 0.5
```

Hope it helps ;)
