### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by Stupco** [danielwelch/hassio-zigbee2mqtt#357]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
Current version: 1.14.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Home Assistant running on Raspberry Pi 3 B+ with a flashed CC2531 Zigbee Stick

name | value
--- | ---
arch | armv7l
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.7.7
supervisor | 228
version | 0.112.2
virtualenv | false

**Description of problem:**
Can't start the add on :(

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.xxx.x.xxx:1883'
  user: user
  password: password
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001949C387-if00
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Hass.io**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-07-16T11:30:19: PM2 log: Launching in no daemon mode
2020-07-16T11:30:20: PM2 log: App [npm:0] starting in -fork mode-
2020-07-16T11:30:20: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.1 start /zigbee2mqtt-1.14.1
> node index.js
zigbee2mqtt:info  2020-07-16 11:30:28: Logging to console and directory: '/share/zigbee2mqtt/log/2020-07-16.11-30-28' filename: log.txt
zigbee2mqtt:info  2020-07-16 11:30:29: Starting zigbee2mqtt version 1.14.1 (commit #unknown)
zigbee2mqtt:info  2020-07-16 11:30:29: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-07-16 11:30:37: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-07-16 11:30:37: Failed to start zigbee
zigbee2mqtt:error 2020-07-16 11:30:37: Exiting...
zigbee2mqtt:error 2020-07-16 11:30:37: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:72:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.14.1/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.14.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
