### ISSUE TITLE
Image for armhf not found for 1.14.2

### ISSUE THREAD

**Issue by InvertedMinor** [danielwelch/hassio-zigbee2mqtt#365]
The 1.14.2 version does not start

Hassio log

`20-07-25 07:51:12 ERROR (SyncWorker_3) [supervisor.docker] Can't create container from addon_7ad98f9c_zigbee2mqtt: 404 Client Error: Not Found ("No such image: dwelch2101/zigbee2mqtt-armhf:1.14.2")`

Config:
```
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: XXXXX
  password: XXXX
serial:
  port: /dev/ttyACM2
advanced:
  pan_id: 6754
  channel: 15
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: true

````

System:

arch | armv7l
-- | --
chassis |  
dev | false
docker | true
docker_version | 19.03.6
hassio | true
host_os | Raspbian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.19.97-v7l+
python_version | 3.8.3
supervisor | 229
timezone | Europe/Amsterdam
version | 0.113.1
virtualenv | false
