### ISSUE TITLE
Unable to change output format in 1.14.3

### ISSUE THREAD

**Issue by mozoh** [danielwelch/hassio-zigbee2mqtt#371]
I'm trying to configure zigbee2mqtt with the following config field:
```
experimental:
  output: 'attribute_and_json'
```
but seems like it does not work, and i've got the message in the supervisor logs:
```
20-04-18 01:31:57 WARNING (MainThread) [supervisor.addons.validate] Unknown options experimental
```
I am using HassOS 4.12 and addon version 1.14.3

**Comment by ciotlosm** [comment]
@mozoh can you please post your add-on config?

**Comment by mozoh** [comment]
```
data_path: /config/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: my mqtt password
serial:
  port: /dev/ttyACM1
advanced:
  pan_id: 6754
  channel: 11
  network_key: my network key
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
experimental:
  output: attribute_and_json
```
