### ISSUE TITLE
Upgraded to 1.14.4.1 and my zigbee2mqtt won't start

### ISSUE THREAD

**Issue by dnedeltchev** [danielwelch/hassio-zigbee2mqtt#390]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

**Description of problem:**
zigbee2mqtt won't start. When I click start it tell me this

Failed to start addon - configruation validation faled!
Missing option availability_passlist in advanced.

I am unable to change anything in the config at all. So I am unable to add the above option if that is indeed the fix which I doubt. I get errors in the supervisor log that say
zigbee2mqtt Unknown options availability_blacklist

I am unable to remove this option as I am unable to save the config.

I am rebooting the pi now and it looks like I will be doing a restore from 15th Sept.

Looks like someone released a dodgy version...?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
// replace this line with your pasted configuration
```

**Your logs from Home Assistant**

**Comment by dnedeltchev** [comment]
no go after reboot

Error in supervisor log

20-09-17 21:17:31 WARNING (MainThread) [supervisor.addons.validate] Unknown options availability_blacklist
20-09-17 21:17:56 WARNING (MainThread) [supervisor.addons.validate] Unknown options availability_blacklist

Error when I try to start zigbee2mqtt

Failed to start addon - configruation validation faled!
Missing option availability_passlist in advanced.

Error if I try to save any changes to the config file

Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'external_converters': [], 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt', 'server': 'mqtt://core-mosquitto', 'user': 'xxxxxx', 'password': 'xxxxxx'}, 'serial': {'port': '/dev/ttyACM0'}, 'advanced': {'pan_id': xxxx, 'channel': x, 'network_key': [xxxxxxxxx], 'availability_blacklist': [], 'availability_passlist': []}, 'devi...

Looks like a restore

**Comment by elliotmoso** [comment]
On your Configuration
add `availability_passlist: []` in your advanced section

**Comment by dnedeltchev** [comment]
Done that but I am unable to save the config. I get an error. See my second post. Also in my supervisor log I get Unknown options availability_blacklist and removing this option, I still can't save the config. Doing a restore now unfortunately.

**Comment by lukaszq** [comment]
> On your Configuration
> add `availability_passlist: []` in your advanced section

When add availability_passlist: [] Error:

Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'external_converters': [], 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': True, 'mqtt': {'base_topic': 'zigbee2mqtt', 'server': 'mqtt://core-mosquitto', 'user': 'mqtt1', 'password': 'mqtt1'}, 'serial': {'port': '/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B000BE8B10F-if00'}, 'advanced': {'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13], 'ava...

**Comment by elliotmoso** [comment]
I think `availability_blacklist` has been renamed to `availability_blocklist`

**Comment by shirou93** [comment]
don't work @elliotmoso

**Comment by pvermeij** [comment]
Had the same issue.
You indeed need to change availability_blacklist to availability_blocklist and add availability_passlist to the advanced section

**Comment by mj1985** [comment]
Same error here, I copied my config and pushing "Reset to defaults", I was able to start the addon again:
My new config:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: xxxxx
  password: xxxx
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CB_F1_16-if00-port0
advanced:
  log_level: info
  pan_id: XXXX
  channel: 11
  network_key:
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```
I stripped the network-key and pan-id.
