### ISSUE TITLE
Zigbee USB setup

### ISSUE THREAD

**Issue by oldfart101** [danielwelch/hassio-zigbee2mqtt#398]
I have a zigbee Texas Instruments CC2531 usb
inserting it into a bare-metal linux pc results in a directory being created:
`/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D956FC-if00`

inserting it into a raspberry pi running home assistant does not create that directory.

Yet, the system for HA says the device is located in that directory.

I created an issue on HA github, but it has been 'resolved' because the device works.
It just cannot be accessed by anything else because the directory does not exist.

I fail to understand how the device works, when pointers are not correct.

**Comment by ciotlosm** [comment]
@oldfart101  Can you post the content from: `Home Assistant` → `Supervisor` → `System` → `Host System` → ⋮ → `Hardware` when the stick is in your RPI?

From where do you want to access the USB stick? If from another add-on, you must make sure that it has `uart: true`. It's really important to understand that you can't access directly hardware devices from the Host inside containers, you must map them.

**Comment by oldfart101** [comment]
My problem is zigbee2mqtt can't see the directory, I get error:
Zigbee2MQTT:error 2020-09-21 10:27:10: Error: Failed to connect to the adapter 

where should the line uart:true be put?

output of hardware:

serial:
  - /dev/ttyACM0
  - >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D956FC-if00
  - /dev/ttyAMA0
input: []
disk:
  - /dev/mmcblk0
  - /dev/mmcblk0p1
  - /dev/mmcblk0p2
  - /dev/mmcblk0p3
  - /dev/mmcblk0p4
  - /dev/mmcblk0p5
  - /dev/mmcblk0p6
  - /dev/mmcblk0p7
  - /dev/mmcblk0p8
gpio:
  - gpiochip504
  - gpiochip0
usb:
  - /dev/bus/usb/001/001
  - /dev/bus/usb/001/002
  - /dev/bus/usb/001/004
  - /dev/bus/usb/002/001
audio:
  '0':
    name: bcm2835_alsa - bcm2835 ALSA
    type: ALSA
    devices:
      - chan_id: '0'
        chan_type: digital audio playback
      - chan_id: '1'
        chan_type: digital audio playback
      - chan_id: '2'
        chan_type: digital audio playback

**Comment by oldfart101** [comment]
@ciotlosm - thanks for editing my post

**Comment by ciotlosm** [comment]
@oldfart101 can you post you `zigbee2mqtt` addon config?

**Comment by oldfart101** [comment]
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: '192.168.1.10:1885'
  user: spare-server
  password: fred
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D956FC-if00
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```
