### ISSUE TITLE
Error while starting zigbee-herdsman - Npm Error

### ISSUE THREAD

**Issue by thomasgermain** [danielwelch/hassio-zigbee2mqtt#433]
**zigbee2mqtt add-on version (if edge, please report commit hash):** 1.15.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
HassOS 4.13
Conbee II

**Description of problem:**
The addon doesn't start.
It seems quite hard to me to identify what I can do. The HA logs says there is a npm debug file here `/root/.npm/_logs/2020-10-01T20_55_06_357Z-debug.log`, but is there any way to access the file inside the container ?

I also found this issue https://github.com/Koenkk/zigbee2mqtt/issues/2333, saying it can be related to permissions, but I expect the addon to do it for me (let me know if i'm wrong, I'm a bit outside my comfort zone with docker).

I also tried the deCONZ add on and this is working as expected, but I would really like to go to zigbee2mqtt

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```yaml
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto:1883'
  user: '!secret mqtt_username'
  password: '!secret mqtt_password'
  include_device_information: true
serial:
  port: /dev/ttyAMA0
  adapter: deconz
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - [redacted]
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-10-01T22:53:37: PM2 log: Launching in no daemon mode
2020-10-01T22:53:37: PM2 log: App [npm:0] starting in -fork mode-
2020-10-01T22:53:37: PM2 log: App [npm:0] online
> zigbee2mqtt@1.15.0 start /zigbee2mqtt-1.15.0
> node index.js
Zigbee2MQTT:info  2020-10-01 22:53:51: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-01.22-53-51' filename: log.txt
Zigbee2MQTT:info  2020-10-01 22:53:56: Starting Zigbee2MQTT version 1.15.0 (commit #1.15.0)
Zigbee2MQTT:info  2020-10-01 22:53:56: Starting zigbee-herdsman...
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2020-10-01 22:54:08: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-01 22:54:08: Failed to start zigbee
Zigbee2MQTT:error 2020-10-01 22:54:08: Exiting...
Zigbee2MQTT:error 2020-10-01 22:54:08: undefined
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.15.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.15.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-01T20_55_06_357Z-debug.log
2020-10-01T22:55:08: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-10-01T22:55:08: PM2 log: App [npm:0] starting in -fork mode-
2020-10-01T22:55:08: PM2 log: App [npm:0] online
```
