### ISSUE TITLE
bad gateway

### ISSUE THREAD

**Issue by gald33** [danielwelch/hassio-zigbee2mqtt#453]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.15.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

**Description of problem:**
"Error 502: bad gateway" when I go to the addon (relative url: /7ad98f9c_zigbee2mqtt)

**more info:**

I used the same zigbee usb stick successfully with zigbee2mqtt (not the HA addon) a few days ago on another OS.
I added myself to the dialout group, and chown the device just in case.

What does this error mean?

Things I've tried:
- restarting the addon.
- waiting 20hrs.
- testing the usb dongle has write permission: after first command I connected the device
```
$ ls /dev/tty* >> ./temp/1.txt
$ ls /dev/tty* >> ./temp/2.txt
$ cd temp
$ diff 1.txt 2.txt 
65a66
> /dev/ttyACM0
$ test -w /dev/ttyACM0 && echo "write permission on" || echo "write permission off"
write permission on
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
haven't changed anything:

data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: my_user
  password: my_password
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
Addon logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-10-27T09:35:52: PM2 log: Launching in no daemon mode
2020-10-27T09:35:52: PM2 log: App [npm:0] starting in -fork mode-
2020-10-27T09:35:52: PM2 log: App [npm:0] online
> zigbee2mqtt@1.15.0 start /zigbee2mqtt-1.15.0
> node index.js
Zigbee2MQTT:info  2020-10-27 09:35:52: Logging to console and directory: '/share/zigbee2mqtt/log/2020-10-27.09-35-52' filename: log.txt
Zigbee2MQTT:info  2020-10-27 09:35:52: Starting Zigbee2MQTT version 1.15.0 (commit #1.15.0)
Zigbee2MQTT:info  2020-10-27 09:35:52: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-10-27 09:36:33: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-27 09:36:33: Failed to start zigbee
Zigbee2MQTT:error 2020-10-27 09:36:33: Exiting...
Zigbee2MQTT:error 2020-10-27 09:36:33: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.15.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:92:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.15.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
 zigbee2mqtt@1.15.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.15.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
