### ISSUE TITLE
Devices become unavailable, only add-on restart helps

### ISSUE THREAD

**Issue by KixMan28** [danielwelch/hassio-zigbee2mqtt#464]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
1.16.1
**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

**Description of problem:**
Yesterday my devices became unavailable for 3 hours, then they came back without doing anything special. Today again they became unavailable at around 10:30 and since them they are stil in that state. Both the zigbee2mqtt add-on and the Mosquito Broker add-on show no errors in the logs. Restarting the Mosquito Broker doesn't solve the problem. To solve the problem I need to restart the zigbee2mqtt add-on.

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```yaml
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: '!secret kixmqtt_user
  password: '!secret kixmqtt_psw'
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E2055D-if00
advanced:
  log_level: info
  pan_id: 6754
  channel: 14
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
Logger: homeassistant.components.mqtt
Source: components/mqtt/__init__.py:1015
Integration: MQTT (documentation, issues)
First occurred: 10:50:30 AM (2 occurrences)
Last logged: 5:26:58 PM

Disconnected from MQTT server core-mosquitto:1883 (1)
