### ISSUE TITLE
ZigBee command not working anymore

### ISSUE THREAD

**Issue by sybux2000** [danielwelch/hassio-zigbee2mqtt#465]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**

Hassio under docker in version 0.117.5
ZigBee2Mqtt inside Hassio in version 1.16.1
Mosquitto MqttBroker of hassio version 5.1

**Description of problem:**
since I think update to release 1.16, all my zigbee device are not working anymore. I can get a map of all device but I can't send command as show bellow in logs

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```yaml
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://myip:myport'
  user: myuser
  password: mypass
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: myport
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**
```
Zigbee2MQTT:error 2020-11-09 22:26:38: Publish 'set' 'state' to 'mydeviceID' failed: 'Error: Command mydeviceID/11 genOnOff.on
({},
{
    "timeout": 10000,
    "disableResponse": false,
    "disableRecovery": false,
    "disableDefaultResponse": false,
    "direction": 0,
    "srcEndpoint": null,
    "reservedBits": 0,
    "manufacturerCode": null,
    "transactionSequenceNumber": null
}) 
failed (SREQ '--> AF - dataRequest - {
    "dstaddr": 36657,
    "destendpoint": 11,
    "srcendpoint": 1,
    "clusterid": 6,
    "transid": 10,
    "options": 0,
    "radius": 30,
    "len": 3,
    "data": {
        "type": "Buffer",
        "data": [
            1,
            8,
            1
        ]
    }
}' 
failed with status '(0x02: INVALID_PARAM)' (expected '(0x00: SUCCESS)'))'
```
