### ISSUE TITLE
Not all device data is exposed in HA

### ISSUE THREAD

**Issue by worker72** [danielwelch/hassio-zigbee2mqtt#469]
In the GUI (frontend?) of zigbee2mqtt, the STATE tab shows a variable called pi_heating_demand (and more) which is not shown in HA environment. (see 2 screenshots)

How can I access such hidden variables?

![image](https://user-images.githubusercontent.com/1201336/99257944-1d402000-2818-11eb-9f77-8a8ecb9ed513.png)
![image](https://user-images.githubusercontent.com/1201336/99258024-3a74ee80-2818-11eb-99a6-18dc50ef71a5.png)

**Comment by lovelylain** [comment]
add below configuration to `configuration.yaml`
```
sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.pi_heating_demand }}"
    icon: "mdi:gesture-double-tap"
```
