### ISSUE TITLE
Z2M - 502: Bad Gateway - unknown options zigbee_herdsman_debug

### ISSUE THREAD

**Issue by Uncaged77** [danielwelch/hassio-zigbee2mqtt#494]
Hello,

Getting 502: Bad Gateway error when clicking the addon in HA

Using Conbee 2 stick with updated firmware.
HA Addon: Zigbee2mqtt Current version: 1.16.2.2
HA on a VM in VirtualBox sitting on a windows 10 machine.
Mosquitto broker: Current version: 5.1

Getting this log when looking at the addin log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-12-10T13:26:00: PM2 log: Launching in no daemon mode
2020-12-10T13:26:00: PM2 log: App [npm:0] starting in -fork mode-
2020-12-10T13:26:00: PM2 log: App [npm:0] online
> zigbee2mqtt@1.16.2 start /zigbee2mqtt-1.16.2
> node index.js
Zigbee2MQTT:info  2020-12-10 13:26:06: Logging to console and directory: '/share/zigbee2mqtt/log/2020-12-10.13-26-04' filename: log.txt
Zigbee2MQTT:info  2020-12-10 13:26:06: Starting Zigbee2MQTT version 1.16.2 (commit #1.16.2)
Zigbee2MQTT:info  2020-12-10 13:26:06: Starting zigbee-herdsman (0.13.37)
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2020-12-10 13:26:17: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-12-10 13:26:17: Failed to start zigbee
Zigbee2MQTT:error 2020-12-10 13:26:17: Exiting...
Zigbee2MQTT:error 2020-12-10 13:26:17: undefined
npm
 
ERR! code ELIFECYCLE
npm ERR! 
errno 1
npm
 
ERR! zigbee2mqtt@1.16.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.16.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-10T18_26_17_690Z-debug.log
2020-12-10T13:26:19: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
```

Config in the addon:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqttuser
  password: mqttuser
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2253025-if00
  adapter: deconz
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
  zigbee_herdsman_debug: true
```
HA LOG:
```
20-12-10 18:25:57 WARNING (MainThread) [supervisor.addons.validate] Unknown options zigbee_herdsman_debug
20-12-10 18:25:58 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on dwelch2101/zigbee2mqtt-amd64 with version 1.16.2.2
20-12-10 18:27:47 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:8099 ssl:default [Connect call failed ('172.30.33.1', 8099)]
```

**Comment by nicog2** [comment]
Hello,

I have the same pb

**Comment by eric-zimmer** [comment]
I habe also the same problem

**Comment by Uncaged77** [comment]
Well, i dont seem to be getting any support from any avenue so i am returning the stick to amazon, its all packed up and ready to go, I guess i'll be looking for a different solution.

**Comment by jjwbruin** [comment]
Hi, I have also the same problem. 
If I use the usb drive on a windows platform it is working just fine. So it has to be a problem with HA....

**Comment by CheekyMonkeyPo** [comment]
Similar problem here. I'm finding it hard to configure Zigbee kit, and the 502 is an intermittant but frequent problem. Sometimes sovled by a restart, but sometimes not. I think its to do with zigbee-herdsman not starting? Log as below but I can't take it any further. Does this help anyone??

Zigbee2MQTT:info  2020-12-18 15:16:40: Starting zigbee-herdsman (0.13.37)
Zigbee2MQTT:error 2020-12-18 15:17:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-12-18 15:17:18: Failed to start zigbee
Zigbee2MQTT:error 2020-12-18 15:17:18: Exiting...
Zigbee2MQTT:error 2020-12-18 15:17:18: Error: AREQ - SYS - resetInd after 30000ms
    at Timeout._onTimeout (/zigbee2mqtt-1.16.2/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by ciotlosm** [comment]
@Uncaged77 Your error is `Unknown options zigbee_herdsman_debug`. Please remove `zigbee_herdsman_debug: true` from your config, and add-on should start. The option was documented to have been removed in a version intermediate from which you updated. 

Apologies for coming back later with answer, however this is still an open source project where people volunteer their time trying to do things best effort, I hope you understand.

@nicog2 @eric-zimmer the error with 502 is because the add-on didn't start for some reason. Unless you post some logs, yours might be completely different error. 

@jjwbruin it depends on your config and what you have configured as serial port. Without an issue with logs, we can't know for sure what exactly is happening. 

@CheekyMonkeyPo 502 is related to add-on either not starting, or starting late. `Error: AREQ - SYS - resetInd after 30000ms` points to a problem between Zigbee2mqtt and your Zigbee kit. This is probably better reported on the main Zigbee2mqtt issue tracker.

**Comment by benwedel-snabble** [comment]
see #513 ???

**Comment by galligan** [comment]
Seem to be having the same, or a similar problem. No matter what I do I can't seem to debug this thing and it's quite frustrating.

Attempting to use a Conbee II with an Intel NUC. I've tried both ACM and full identifier for the serial port. 

Here's my log:

```
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-06T14_28_12_848Z-debug.log
[09:28:13] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2021-03-06 09:28:13: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-06 09:28:13: Failed to start zigbee
Zigbee2MQTT:error 2021-03-06 09:28:13: Exiting...
Zigbee2MQTT:error 2021-03-06 09:28:13: Error: Error while opening serialport 'Error: Error: Resource busy, cannot open /dev/ttyACM1'
    at Driver.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:157:28)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:155:45)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-06T14_28_13_873Z-debug.log
[09:28:13] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2021-03-06 09:28:14: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-06 09:28:14: Failed to start zigbee
Zigbee2MQTT:error 2021-03-06 09:28:14: Exiting...
Zigbee2MQTT:error 2021-03-06 09:28:14: Error: Error while opening serialport 'Error: Error: Resource busy, cannot open /dev/ttyACM1'
    at Driver.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:157:28)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:155:45)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-06T14_28_14_853Z-debug.log
[09:28:15] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2021-03-06 09:28:15: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-06 09:28:15: Failed to start zigbee
Zigbee2MQTT:error 2021-03-06 09:28:15: Exiting...
Zigbee2MQTT:error 2021-03-06 09:28:15: Error: Error while opening serialport 'Error: Error: Resource busy, cannot open /dev/ttyACM1'
    at Driver.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:157:28)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:155:45)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-06T14_28_15_892Z-debug.log
[09:28:15] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.17.1 start /app
> node index.js
```

And here is my config:

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: [REDACTED]
  password: [REDACTED]
serial:
  port: /dev/ttyACM1
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false

```
