### ISSUE TITLE
Zigbee2mqtt refuses to see / connect to conbee II

### ISSUE THREAD

**Issue by WesNz** [danielwelch/hassio-zigbee2mqtt#513]
Zigbee2mqtt refuses to recognize the the Conbee II usb

Deconz can see and connect to the conbee II no issues.
Zigbeemqtt wont see /connect to the conbee II
But....if i have deconz running....and then start zigbeemqtt....zigbeemqttt reports "device busy"

Operating environment : HassOS vm on qnap.

**Description of problem:**
I can see the conbee II in  /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE*****-if00 and /devttyACM0

I have tried both paths above for the configuration, no luck

**Your logs from Home Assistant**
```
Zigbee2MQTT:info  2021-01-09 12:51:36: Starting Zigbee2MQTT version 1.17.0 (commit #1.17.0)
Zigbee2MQTT:info  2021-01-09 12:51:36: Starting zigbee-herdsman (0.13.46)
Zigbee2MQTT:error 2021-01-09 12:51:55: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-01-09 12:51:55: Failed to start zigbee
Zigbee2MQTT:error 2021-01-09 12:51:55: Exiting...
Zigbee2MQTT:error 2021-01-09 12:51:55: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm 
ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
 zigbee2mqtt@1.17.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-08T23_51_55_944Z-debug.log
2021-01-09T12:51:57: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2021-01-09T12:51:57: PM2 log: App [npm:0] starting in -fork mode-
2021-01-09T12:51:57: PM2 log: App [npm:0] online
> zigbee2mqtt@1.17.0 start /zigbee2mqtt-1.17.0
> node index.js
```

** Config
```
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE*****-if00
advanced:
  log_level: info
```

**Comment by benwedel-snabble** [comment]
same issue here!
I'm new to this - but if you need any information - i'd like to help

I've tried a whole lot more, a couple of times. 

Set up: RaspberryPi 4 B, Conbee 2 ; Hass.io, Mosquitto, Zigbee2mqtt (individual add-on by danielwelch)
Problem: After setup and configuration the frontend shows: 502 Bad Gateway / Problem to connect to USB-Serial Port?!

Zigbee2mqtt keeps on telling me (LOG):

Zigbee2MQTT:info  2021-01-09 00:53:52: Starting zigbee-herdsman (0.13.46)
Zigbee2MQTT:error 2021-01-09 00:54:12: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-01-09 00:54:12: Failed to start zigbee
Zigbee2MQTT:error 2021-01-09 00:54:12: Exiting...
Zigbee2MQTT:error 2021-01-09 00:54:12: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)

**Comment by WesNz** [comment]
@&#&#%@&@. figured out i needed `adapter: deconz` in the config file @benwedel-snabble

**Comment by benwedel-snabble** [comment]
> @&#&#%@&@. figured out i needed `adapter: deconz` is the config file @benwedel-snabble

Sorry, what do you mean?

**Comment by pvermeij** [comment]
See [https://www.zigbee2mqtt.io/information/supported_adapters.html](https://www.zigbee2mqtt.io/information/supported_adapters.html) and scroll down to Conbee II for more information regarding this issue and how to solve it.

**Comment by benwedel-snabble** [comment]
Wow!!!! Thanks a lot - it‘s actually working with that! ✌🏽🙌🏽

**Comment by ciotlosm** [comment]
Can this issue be closed?

**Comment by kvmgz** [comment]
I have the right serial: port & adapter, but still getting these errors... very annoying...

**Comment by JaCoLJcL** [comment]
I have the same isssue :(

**Comment by ciotlosm** [comment]
@JaCoLJcL @kvmgz can you post logs for your errors? You might have different problems than the missing settings for adapter as the poster above.

**Comment by galligan** [comment]
Same issue here too unfortunately. Posted my logs here @ciotlosm: https://github.com/danielwelch/hassio-zigbee2mqtt/issues/494#issuecomment-791962197

**Comment by WesNz** [comment]
> Same issue here too unfortunately. Posted my logs here @ciotlosm: [#494 (comment)](https://github.com/danielwelch/hassio-zigbee2mqtt/issues/494#issuecomment-791962197)

Your error is different :  Error: Error while opening serialport 'Error: Error: Resource busy, cannot open /dev/ttyACM1


Paste your config file for the addon

**Comment by kraton77** [comment]
I have the same problem, I found out that I have to turn off DeConz and then run zigbee2mqtt.

**Comment by galligan** [comment]
@WesNz Here's my config file:

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: [REDACTED]
  password: [REDACTED]
serial:
  port: /dev/ttyACM1
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```

@kraton77 That's interesting—I have ZHA running on a completely different stick entirely (that's incompatible with Z2MQTT). Still, I've never configured ZHA with the Conbee I'm trying to run z2m on.

**Comment by WesNz** [comment]
@mg0716 

here's my config file below ...i see your Port: is different?
the main thing that strikes me with your error message is its saying that your device is busy...which means a) some app or something is using the device.. or b) you are pointing to the wrong device?

maybe easiest to test without the usb first and see if u getting the same error?

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.178.17:1883'
  user: meh
  password: meh
serial:
  adapter: deconz
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2253437-if00
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Comment by galligan** [comment]
Thanks @WesNz. Now I feel like an **absolute idiot**. It turns out that I never turned off Deconz 😑🙄🤦🏼‍♂️. Safe to say, it's running now lol.

**Comment by mandolinhobbit** [comment]
I have the same issue, and I have devices that will only work with Zigbee2Mqtt (Philips Hue PAR38 outdoor flood bulbs) so DeConz is not an option for me.

Config file:
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2469763-if00
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
server: mqtt://192.168.x.xxx [it has the correct ip address]

Logfile:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:41:03] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[13:41:04] INFO: MQTT available, fetching server detail ...
[13:41:04] INFO: MQTT server settings not configured, trying to auto-discovering ...
[13:41:04] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[13:41:05] INFO: MQTT credentials not configured, trying to auto-discovering ...
[13:41:05] INFO: Configuring'addons' mqtt user
[13:41:05] INFO: Previous config file found, checking backup
[13:41:05] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[13:41:05] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:41:06] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
Zigbee2MQTT:error 2022-01-03 13:41:33: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-03 13:41:33: Failed to start zigbee
Zigbee2MQTT:error 2022-01-03 13:41:33: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-03 13:41:33: Exiting...
Zigbee2MQTT:error 2022-01-03 13:41:33: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
[13:41:34] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js

I tried to add the below lines to my configuration.yaml file:
serial:
  adapter: deconz

However, that just gives me an Invalid Config notification:
Invalid config
The following integrations and platforms could not be set up:

serial

**Comment by atv2016** [comment]
@ciotlosm @WesNz @mg0716 how does one turn off deconz? I removed all the devices from there but it still autodiscovers stuff. 

I have a feeling this is why I am getting the same error in zigbee2mqtt.

**Comment by octave-ati** [comment]
I have the exact same issue and error message, I used to run my Conbee through Deconz but I don't know how to turn it off

**Comment by atv2016** [comment]
I had to add serial: deconz to my zigbeemqtt yank configuration file. It’s sort of hidden away in the docs, but it’s on the zigbeemqtt website.

**Comment by octave-ati** [comment]
Already have that, here is my config : 

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2467521-if00
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```
