### ISSUE TITLE
Unable to update zigbee2mqtt hassio add-on

### ISSUE THREAD

**Issue by marothe** [danielwelch/hassio-zigbee2mqtt#520]
**zigbee2mqtt add-on version (if edge, please report commit hash):**
Current version: 1.12.0

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):**
Home Assistant running on a Raspberry Pi through the official image.

Version
core-2021.1.3

Version
supervisor-2021.01.4

Operating System
Home Assistant OS 5.10

**Description of problem:**
I installed the Z2M add-on for hassio, now Home Assistant, and it works. Problem: I see no ability to update? I am stuck on 1.12.0 whereas the newest version is 1.17.X I guess? How to I update?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.XXX.XX:1883'
  user: XXXX
  password: XXXX
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Your logs from Home Assistant**

No logs. I just cannot update. 
![image](https://user-images.githubusercontent.com/29024610/105578766-ca886480-5d82-11eb-8d40-9e339e2f000d.png)

**Comment by whoisdecoy** [comment]
Receiving similar error `Repostitory structure for v1.17.0.1 is not compliant` when adding repo to install for first time.

**Comment by caddyblack** [comment]
In the picture of your Homeassistant Zigbee2mqtt I see Auto update switchen off ( above the Restart button).
I have the Auto update enabled and do get update versions.

**Comment by marothe** [comment]
Thanks for the answer @caddyblack! I did turn it on, but that does not change anything :( 

![image](https://user-images.githubusercontent.com/29024610/106467938-978a5300-649d-11eb-8367-678bb8503c04.png)

**Comment by andres-a-git** [comment]
Do I have a similar issue? I am not able to update or install anymore the zigbee2mqtt.
Luckily I was able to use the snapshot for previous working version

The 1.17.0.1 worked, but ine Xiaomi plug was acting strange. So somehow after several tries I was able to update to 1.17.1, but was not able to start theadd-on. After this I did a uninstall and now I am not able to re-install byhaving an error:

404 Client Error for http+docker://localhost/v1.40/images/dwelch2101/zigbee2mqtt-aarch64:1.17.1/json: Not Found ("no such image: dwelch2101/zigbee2mqtt-aarch64:1.17.1: No such image: dwelch2101/zigbee2mqtt-aarch64:1.17.1")

Log:
21-02-07 11:00:15 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image dwelch2101/zigbee2mqtt-aarch64 with tag 1.17.1.
21-02-07 11:01:09 ERROR (SyncWorker_5) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-aarch64:1.17.1 -> 404 Client Error for http+docker://localhost/v1.40/images/dwelch2101/zigbee2mqtt-aarch64:1.17.1/json: Not Found ("no such image: dwelch2101/zigbee2mqtt-aarch64:1.17.1: No such image: dwelch2101/zigbee2mqtt-aarch64:1.17.1").


There looks to be sufficient disk space:
![image](https://user-images.githubusercontent.com/59292628/107144669-61d5e600-6945-11eb-8653-f7b8af866fde.png)

System runs the 64-bit official Raspberry verion from SSD:
![image](https://user-images.githubusercontent.com/59292628/107144720-b5e0ca80-6945-11eb-8e08-39a8ba938d63.png)


Previous setup was like this:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: XXXXX
  password: XXXXX
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 11
  log_level: debug
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```
