### ISSUE TITLE
Zigbee2MQTT:error

### ISSUE THREAD

**Issue by 4noxx** [danielwelch/hassio-zigbee2mqtt#539]
hello, have some problems to start this addon:

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T09_08_21_475Z-debug.log
[11:08:21] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.2 start /app
> node index.js
Zigbee2MQTT:error 2021-04-23 11:08:45: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-04-23 11:08:45: Failed to start zigbee
Zigbee2MQTT:error 2021-04-23 11:08:45: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-04-23 11:08:45: Exiting...
Zigbee2MQTT:error 2021-04-23 11:08:45: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T09_08_45_983Z-debug.log
[11:08:46] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.2 start /app
> node index.js
Zigbee2MQTT:error 2021-04-23 11:09:11: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-04-23 11:09:11: Failed to start zigbee
Zigbee2MQTT:error 2021-04-23 11:09:11: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-04-23 11:09:11: Exiting...
Zigbee2MQTT:error 2021-04-23 11:09:11: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T09_09_11_178Z-debug.log
[11:09:12] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.2 start /app
> node index.js
Zigbee2MQTT:error 2021-04-23 11:09:38: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-04-23 11:09:38: Failed to start zigbee
Zigbee2MQTT:error 2021-04-23 11:09:38: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-04-23 11:09:38: Exiting...
Zigbee2MQTT:error 2021-04-23 11:09:38: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T09_09_38_854Z-debug.log
[11:09:42] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.2 start /app
> node index.js
Zigbee2MQTT:error 2021-04-23 11:10:07: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-04-23 11:10:07: Failed to start zigbee
Zigbee2MQTT:error 2021-04-23 11:10:07: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-04-23 11:10:07: Exiting...
Zigbee2MQTT:error 2021-04-23 11:10:07: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T09_10_07_435Z-debug.log
[11:10:07] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.2 start /app
> node index.js
```

config:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.1.8:1883'
  user: mqtt_user
  password: mqtt_pass
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2404008-if00
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```
