### ISSUE TITLE
502:  Bad gateway on new install with Con Bee 2 as addon to HA placed on VM

### ISSUE THREAD

**Issue by Ernst10717900** [danielwelch/hassio-zigbee2mqtt#545]
I can't fix my problem need help.
I was migrating from intgrated zigbee to zigbee2mqtt 
I uninstaled my zigbee before installing but no succes for day's

[Config file.txt](https://github.com/danielwelch/hassio-zigbee2mqtt/files/7754925/Config.file.txt)

Thanks in advanced Ernst

**Comment by Bascht74** [comment]
Try to find out the correct port of your device (in HA got to Settings -> Supervisor -> System --> 3 dots @ host --> Hardware: 

![image](https://user-images.githubusercontent.com/66269310/147238304-7f0dea8f-f94f-4bef-b4b9-59d88410b58c.png)


Change the configuration to the shown device like this in your config:
Be sure to add `adapter: deconz` if you have a Conbee adapter. Look here: 
https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html

```
# Optional: adapter type, not needed unless you are experiencing problems (default: shown below, options: zstack, deconz, ezsp)
  adapter: null
```

```
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DExxxxxxx-if00
  adapter: deconz
```
