### ISSUE TITLE
Addon config not working

### ISSUE THREAD

**Issue by james-fry** [danielwelch/hassio-zigbee2mqtt#9]
I was expecting the addon config JSON to be written as configuration.yaml in the data_path dir (where the app looks for it).

e.g. 
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": true,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.1.10:1883",
  "serial_port": "/dev/ttyACM0",
  "mqtt_user": "sensors",
  "mqtt_pass": "xxxxxxxx"
}

would be written out as:

```
# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://192.168.1.10:1883'
  # MQTT server authentication, uncomment if required:
  user: sensors
  password: xxxxxxxx

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0

# Advanced configuration
```
...
...

Did I misinterpret what the config is used for? Or is this a WIP?
