### ISSUE TITLE
Node js error at startup: 'Cannot read property 'close' of undefined'

### ISSUE THREAD

**Issue by Sholofly** [danielwelch/hassio-zigbee2mqtt#97]
Hi Daniel,
Some people, including me,  are experiencing the issue below. I've tried te restart and resinstall the addon on hassio but without luck. Can you take a look at this?

p.s.: The edge version has the same error.

HA: 0.86.3
add-on: 1.1.0

@danielwelch 
I'm getting this error now:
``` 
zigbee2mqtt:info 2019-1-31 06:14:03 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
/zigbee2mqtt-1.1.0/node_modules/q/q.js:155
                throw e;
                ^
TypeError: Cannot read property 'close' of undefined
    at shepherd.start (/zigbee2mqtt-1.1.0/lib/zigbee.js:45:47)
    at /zigbee2mqtt-1.1.0/node_modules/q/q.js:2059:17
    at runSingle (/zigbee2mqtt-1.1.0/node_modules/q/q.js:137:13)
    at flush (/zigbee2mqtt-1.1.0/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)```

_Originally posted by @noxhirsch in https://github.com/danielwelch/hassio-zigbee2mqtt/issues/95#issuecomment-459218637_

**Comment by danielwelch** [comment]
Thanks for opening up a new issue and providing more info. Would you mind posting your add-on configuration as well?

**Comment by Claypaenguin** [comment]
I'm having the same issue although it didn't happen right off the bat after updating, but after a couple of hours.

If you want to have a look at my config (I deleted my devices)
```
advanced:
  channel: 25
  log_level: debug
  network_key:
  - 17
  - 12
  - 76
  - 207
  - 51
  - 2
  - 79
  - 13
  - 195
  - 16
  - 243
  - 43
  - 5
  - 133
  - 69
  - 17
devices:
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  password: password
  server: mqtt://homeassistant
  user: mqtt
permit_join: false
serial:
  port: /dev/ttyACM0
```
